### ISSUE TITLE
As long as we need to migrate resources we need to activate them in the CI

### ISSUE THREAD

**Issue by ccamacho** [os-migrate/os-migrate#129]
Configured as:

# Pre-requisite
ENABLED_SERVICES=mysql,key
# Neutron
ENABLED_SERVICES+=,q-svc,q-agt,q-dhcp,q-l3,q-meta,neutron

When we add i.e. Nova functionalities it might not work on the CI depending on what we need to deploy.

This will probably affect flavors export/import.

**Comment by jistr** [comment]
I think we CI everything now as possible, e.g. the mentioned flavors do have a functional CI.
