### ISSUE TITLE
Subnet import fails on functional tests - subnet import not idempotent

### ISSUE THREAD

**Issue by ccamacho** [os-migrate/os-migrate#140]
Still failing on subnet import

TASK [import_subnets : import subnets] *****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: openstack.exceptions.BadRequestException: BadRequestException: 400: Client Error for url: http://127.0.0.1:9696/v2.0/subnets/osm_subnet, Cannot update read-only attribute ip_version
failed: [localhost] (item={'_info': {'created_at': '2020-03-26T15:14:23Z', 'id': '286c5f76-2788-4104-a808-391a1c063797', 'network_id': '8593bc62-3f45-46ad-9aeb-5f581a71d778', 'prefix_length': None, 'project_id': '32f2a33cd400488f993795407f9d9d11', 'revision_number': 0, 'segment_id': None, 'subnet_pool_id': None, 'tags': [], 'updated_at': '2020-03-26T15:14:23Z'}, 'params': {'allocation_pools': [{'end': '192.168.0.254', 'start': '192.168.0.2'}], 'cidr': '192.168.0.0/24', 'description': '', 'dns_nameservers': ['8.8.8.7', '8.8.8.8'], 'gateway_ip': '192.168.0.1', 'host_routes': [{'destination': '0.0.0.0/0', 'nexthop': '12.34.56.78'}, {'destination': '192.168.0.0/24', 'nexthop': '192.168.0.1'}], 'ip_version': 4, 'ipv6_address_mode': None, 'ipv6_ra_mode': None, 'is_dhcp_enabled': True, 'name': 'osm_subnet', 'network_name': 'osm_net', 'segment_name': None, 'service_types': [], 'subnet_pool_name': None, 'use_default_subnet_pool': None}, 'type': 'openstack.subnet.Subnet'}) => changed=false
ansible_loop_var: item
item:
_info:
created_at: '2020-03-26T15:14:23Z'
id: 286c5f76-2788-4104-a808-391a1c063797
network_id: 8593bc62-3f45-46ad-9aeb-5f581a71d778
prefix_length: null
project_id: 32f2a33cd400488f993795407f9d9d11
revision_number: 0
segment_id: null
subnet_pool_id: null
tags: []
updated_at: '2020-03-26T15:14:23Z'
params:

**Comment by rbrady** [comment]
really weird.  it's not failing locally in my tests at all.  does it work for anyone else locally?

**Comment by ccamacho** [comment]
Maybe something merged in Devstack that is breaking the execution of the tests? Really weird indeed

**Comment by jistr** [comment]
This bug looks legit, probably intermittent. Getting a successful result doesn't mean it's not there... But we probably need the full logs to decipher what's going on exactly. So still we probably have 2 bugs:

1) non-idempotency on subnet import

2) subnet update is broken

Let's keep this issue for (1) and report a separate for (2)

**Comment by jistr** [comment]
Carlos' PR which was affected by this now passed, i merged it. We still should keep this blocker bug open though, the CI can fail on anything else.
