### ISSUE TITLE
Convert OOP sec group rules to new auth

### ISSUE THREAD

**Issue by ccamacho** [os-migrate/os-migrate#150]
Convert other resources to new auth:

https://github.com/os-migrate/os-migrate/pull/144/files

**Comment by ccamacho** [comment]
Closed by: #148

**Comment by ccamacho** [comment]
Pending sec group rules as they are not merged yet.

**Comment by jistr** [comment]
There's probably nothing left to do here, it only affected the module in #148 i think, not the actual OOP refactor.
