### ISSUE TITLE
Key pairs are not migrated

### ISSUE THREAD

**Issue by ccamacho** [os-migrate/os-migrate#189]
When running a workloads migration the key pairs information is not migrated, you can still connect but if you need these keys again they won't be available.

**Comment by jistr** [comment]
You mean the key pair itself isn't copied to the dst cloud (expected, it's currently an unsupported resource => RFE), or that when the machine is migrated, the original ssh keys don't work?

**Comment by ccamacho** [comment]
@jistr hello, the keys are inside the volume so they are migrated and you can log in.
I created the bug because the key_pair section in the instance is empty, so you won't know which key_pair you need to use to connect. I think is important info, but we can remove the blocker label.

**Comment by jistr** [comment]
The keypair info is now migrated as we've implemented rebuildable instances.
