### ISSUE TITLE
Cant find dst uch guest when importing the workloads

### ISSUE THREAD

**Issue by ccamacho** [os-migrate/os-migrate#199]
From: https://gitlab.cee.redhat.com/os-migrate/bot/-/jobs/1678072#L5315

5301     type: openstack.compute.Server
5302 TASK [import_workloads : get source conversion host address] *******************
5303 ok: [localhost] => changed=false 
5304   openstack_conversion_host:
5305     address: 172.19.13.144
5306     id: 1bf5c221-1de2-4e8a-8b54-c1d1f9405e5b
5307     name: osm_uch_********
5308     status: ACTIVE
5309 TASK [import_workloads : fail if source conversion host is not active] *********
5310 skipping: [localhost] => changed=false 
5311   skip_reason: Conditional result was False
5312 TASK [import_workloads : get destination conversion host address] **************
5313 fatal: [localhost]: FAILED! => changed=false 
5314   msg: Conversion host osm_uch_dst not found!
5315 TASK [1 hour to debug the environment] *****************************************

The filter is not allowing to find the dst uch machine.

Another regression reverted with https://github.com/os-migrate/os-migrate/pull/196/files#diff-797550071aee722b083bad549fa02840L116
Passing on: https://gitlab.cee.redhat.com/os-migrate/bot/-/jobs/1678114#L5316

**Comment by ccamacho** [comment]
Related to: https://github.com/ansible/ansible/issues/54332

**Comment by jistr** [comment]
Fixed

**Comment by jistr** [comment]
Ah no it is the filter issue, not fixed, reopening...

**Comment by ccamacho** [comment]
Not happening in the latest Ansible version we use 3.4
