### ISSUE TITLE
[M3 gate issue] all imports/exports idempotent?

### ISSUE THREAD

**Issue by jistr** [os-migrate/os-migrate#21]
This is so that M1 milestone only gets closed after we verify that export/import of all resources is idempotent.

**Comment by rbrady** [comment]
All resources are currently idempotent.  Not sure of the workload migration idempotence at this time.

**Comment by jistr** [comment]
Thanks, workload migration is its own beast, i'd say let's tackle it when we have the e2e CI for it.

**Comment by jistr** [comment]
Reported https://github.com/os-migrate/os-migrate/issues/185 and we can close this one.
