### ISSUE TITLE
Filter exported resources by name

### ISSUE THREAD

**Issue by jistr** [os-migrate/os-migrate#22]
We should add resource name filtering, to allow some resources to be worked with and others to be left alone.

In theory this can be done in the *transform* phase between import/export, and could be done manually or automated by the operator according to their needs. But there are reasons to include this basic "processing" it in our export tooling directly:

- This is likely to be a very common use case.

- Filtering during-export rather than after-export means that some resources will not get exported at all, which will make the export process faster. This could make a huge difference especially if/when we happen to add some resources which actually contain binary blobs too.

(We should reiterate that our goal is not to add any features for the *transform* phase (operating on the YAML exports), but name-based filtering during export probably makes sense.)

I can imagine operators might want to filter resources in 2 ways: regexp based (e.g. all networks where name starts/ends with something), list based (export only exact name matches in a list). While the latter can be achieved using the former, it would not be comfortable. So i'd suggest filtering by a list of regexes that have an implicit "logical or" operation applied (matching one regex in the list is enough to consider the resource wanted for export).

**Comment by jistr** [comment]
This will simplify functional tests, pulling into M2 from M2 candidates. Maybe we can also ship this with M1 but i don't see it as necessary.

**Comment by jistr** [comment]
Just a data point here: I was wondering whether we should implement custom name-only filtering, or whether we want to just pass-through the `filter` parameter on modules like `os_networks_info`, `os_subnets_info` etc. @ccamacho made me aware that there is no `os_security_groups_info` for example, which suggests we should do custom simple filtering instead of relying on `os_*_info` modules and their consistency.

**Comment by ccamacho** [comment]
@jistr yeahp, im implementing a very simple filter to fetch the current security groups, yet, maybe is simpler to reuse what we have available as os_*_info for i.e. the network export module and build filters for the other cases. In any case, I think what we have for networks should remain. And maybe crea an issue for a posterior refactor.
