### ISSUE TITLE
Document automatically the parameters and defaults for roles and modules

### ISSUE THREAD

**Issue by ccamacho** [os-migrate/os-migrate#250]
We are creating more and more roles with several parameters that should be documented.

We have those sections already documented but not rendered anywhere in the docs.

I propose:

* Render the docs using sphinx+python and upload the result to a branch called gh-pages adding all the roles/modules automatically.
* Have os-migrate.github.io as the docs compiled source.

**Comment by jistr** [comment]
This is done. We should improve the role docs a bit to allow for some custom human-written text too.
