### ISSUE TITLE
Importing to cloud using self signed SSL certificate fails.

### ISSUE THREAD

**Issue by ohlay** [os-migrate/os-migrate#303]
I am testing migration to a new OS cloud that currently only has a self signed SSL certificate. Running the ```import_flavors.yml``` playbook causes the following error:

```Max retries exceeded with url: /v2.1/flavors/m1.tiny (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))```

I assume this could be prevented by running OS CLI commands with the ```--insecure``` flag since this is what I have to do if I want to run any CLI commands manually. Is there a way to set this flag for all the import playbooks?

Kind regards,
Oliver

**Comment by ccamacho** [comment]
Hi @ohlay, first of all, thank you for testing and trying os-migrate!

We actually support this behavior by the following module parameter:

https://github.com/os-migrate/os-migrate/blob/main/os_migrate/roles/import_flavors/tasks/main.yml#L24

Can you make sure you run the playbooks adding both

```
os_migrate_src_validate_certs: False
os_migrate_dst_validate_certs: False
```

Thanks!

**Comment by ohlay** [comment]
Thanks for the quick answer @ccamacho! 
Inserting ```os_migrate_dst_validate_certs: False``` to my os-migrate-vars.yml file solved the problem!
