### ISSUE TITLE
Stop pinning devstack version

### ISSUE THREAD

**Issue by jistr** [os-migrate/os-migrate#34]
We pinned devstack because of #33. We should figure out a way to unpin.

https://github.com/os-migrate/os-migrate/blob/27d16410f2d1eb3f3aec37bf6b815e75a2fdd458/.github/workflows/functional-all.yml#L60-L61

**Comment by ccamacho** [comment]
The fix is on the way to me merged[1], the fix in #39 

[1]: https://review.opendev.org/#/c/704136/1
