### ISSUE TITLE
RFE: When VM migration fails after volumes are copied, do not copy them again

### ISSUE THREAD

**Issue by jistr** [os-migrate/os-migrate#366]
From https://github.com/os-migrate/os-migrate/issues/343#issuecomment-775943727

> if something goes wrong after the volume disk copy (esp, during VM creation in the destination), the re-run starts the disk copy again from the start. It would be helpful, if it detects the disk that is already attached to the conversion host.

**Comment by jistr** [comment]
I think this RFE needs to be approached carefully as the simplest implementation could cause corrupted instances in destination, under specific circumstances. Some thoughts:

* Checking whether the volume exists in destination may not be enough. We'd probably have to introduce some flagging mechanism to tell whether a given volume has already been fully copied over or whether it perhaps failed during copying.

* If the operator decides to recover a failed migration by continuing to use the workload in the source cloud while investigating what went wrong, the right approach is to redo the copy, otherwise destination cloud would create the server from stale data. Even if the import playbook can detect volumes from a failed migration attempt, it probably cannot tell whether the source workload changed since last attempt. This would have to be somehow surfaced to the user via a resource migration parameter or a playbook parameter.

**Comment by jistr** [comment]
If we find we can't do the volume reuse, we should probably at least clean up better after a failed migration, to not leave orphaned volumes?

**Comment by jistr** [comment]
@benyraja I think we are going to default to a better cleanup on failed migration, so that user can retry the playbook without fixing the volume attachements manually (i'm aiming for it in #375 ). However, this could be further improved with some pre-migration checks of the destination cloud state. I think OS Migrate should try to detect potential server creation problems (e.g. missing image or network/subnet) before it even starts copying any data for that workload. So the situation where we first copy the volumes successfully and then discover we can't create the Nova server should become very rare.

**Comment by benyraja** [comment]
@jistr yes, I remember similar situation. After the disk copy, the instance creation failed due to an existing flavor name mismatch.

**Comment by jistr** [comment]
So the clean up in #375 is merged and we've also merged #385 with the destination cloud prerequisites validation. Essentially any resources that are referenced by a Nova server are looked up before the data copying starts, as a validation. So name mismatches in flavor, image, network, subnet etc. would now result in an error before any "real" migration of a given workload starts. This will be released in upcoming version 0.8.0.

**Comment by jistr** [comment]
I'm going to close the issue as we've implemented an alternative approach for the same goal (preventing repeated data transfers due to trivial errors). In case there is some further concern, please let us know.
