### ISSUE TITLE
export_blob misleading comment about chunk_size

### ISSUE THREAD

**Issue by mykaul** [os-migrate/os-migrate#437]
See https://github.com/os-migrate/os-migrate/blob/f049a4d698ed9b1e625864bd7ab2c1c6ba925546/os_migrate/plugins/module_utils/image.py#L183

Writing in 1K blocks is very inefficient, we should strive to use far larger blocks (128K or so) for faster performance.

**Comment by mykaul** [comment]
Is that really 1K, if it's 1024 * 1024 ?

**Comment by jistr** [comment]
Thanks, we need to fix that comment :). I'll rename & reopen the issue.
