### ISSUE TITLE
Need to set availability zone for destination volume 

### ISSUE THREAD

**Issue by tinsjourney** [os-migrate/os-migrate#444]
In my destination cloud there is no default cinder availability zone, and the source AZ doesn't exist in destination.

So we need a parameter to set destination AZ.

**Comment by tinsjourney** [comment]
here's the output of tasks "transfer volumes to destination"


TASK [os_migrate.os_migrate.import_workloads : transfer volumes to destination] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "qemu-img: Could not open 'nbd://localhost:49152/2ed83a39-90d3-4fa8-8f62-c5d7cd2a5585': Failed to connect socket: Connection refused\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1626685660.8770938-499187-235539953437022/AnsiballZ_import_workload_transfer_volumes.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1626685660.8770938-499187-235539953437022/AnsiballZ_import_workload_transfer_volumes.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1626685660.8770938-499187-235539953437022/AnsiballZ_import_workload_transfer_volumes.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.os_migrate.os_migrate.plugins.modules.import_workload_transfer_volumes', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload_mplp1ljj/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_transfer_volumes.py\", line 629, in <module>\n  File \"/tmp/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload_mplp1ljj/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_transfer_volumes.py\", line 625, in main\n  File \"/tmp/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload_mplp1ljj/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_transfer_volumes.py\", line 591, in run_module\n  File \"/tmp/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload_mplp1ljj/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_transfer_volumes.py\", line 332, in transfer_exports\n  File \"/tmp/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload_mplp1ljj/ansible_os_migrate.os_migrate.import_workload_transfer_volumes_payload.zip/ansible_collections/os_migrate/os_migrate/plugins/modules/import_workload_transfer_volumes.py\", line 416, in _create_destination_volumes\n  File \"/root/emine/venv_osmigrate/lib64/python3.6/site-packages/openstack/cloud/_block_storage.py\", line 245, in create_volume\n    raise exc.OpenStackCloudException(\"Error creating volume\")\nopenstack.exceptions.SDKException: Error creating volume\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by jistr** [comment]
This is being addressed in #450 and #456.
