### ISSUE TITLE
export_networks.yml doesn't export any network from cloud

### ISSUE THREAD

**Issue by sigtryggr** [os-migrate/os-migrate#481]
When I start export_networks.yml no available network is found in public interface, though there are networks in project:

ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_timeout": null,
            "auth": {
                "auth_url": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "project_domain_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "project_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "user_domain_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "auth_type": null,
            "availability_zone": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "filters": {
                "project_id": "5196ef4d460b459d805ef7476034c153"
            },
            "interface": "public",
            "name": null,
            "region_name": "RegionOne",
            "timeout": 180,
            "validate_certs": null,
            "wait": true
        }
    },
    "openstack_networks": []
}

# openstack --os-project-id 5196ef4d460b459d805ef7476034c153 network list
+--------------------------------------+---------+--------------------------------------+
| ID                                   | Name    | Subnets                              |
+--------------------------------------+---------+--------------------------------------+
| 85139177-914a-43a0-9087-1423ac471fe9 | public1 | d638adba-4db1-44b5-88da-cf83e5e73900 |
+--------------------------------------+---------+--------------------------------------+

**Comment by jistr** [comment]
Are you running OS Migrate with `os_migrate_src_auth` credentials that have `project_name` of the project that owns the networks you want to export?

**Comment by sigtryggr** [comment]
> Are you running OS Migrate with `os_migrate_src_auth` credentials that have `project_name` of the project that owns the networks you want to export?

Yes, I am

**Comment by philroche** [comment]
@sigtryggr Are you using the same creds for your `openstack --os-project-id 5196ef4d460b459d805ef7476034c153 network list` call as you are for running os-migrate?
