### ISSUE TITLE
"stringfilter" does not appear to work in any situation

### ISSUE THREAD

**Issue by njnatale-lm** [os-migrate/os-migrate#489]
Trying to export from an older OpenStack instance, and regardless of what I'm trying to export, I get errors about filtering.

_Where you see `REMOVED` - that's text I have purposely removed from the message._

### When Exporting Networks

`fatal: [localhost]: FAILED! => {"msg": "stringfilter: value under 'name' in '{u'id': u'REMOVED', u'name': u'********-net'}' is not string: u'********-net'"}`

It appears that something is marked as `no_log` and is causing issues; can this be overridden at all?

### When Exporting KeyPairs, SecurityGroups, etc

`fatal: [localhost]: FAILED! => {"msg": "stringfilter: value under 'name' in '{u'id': u'mykey', u'name': u'mykey'}' is not string: u'mykey'"}`

`fatal: [localhost]: FAILED! => {"msg": "stringfilter: value under 'name' in '{u'id': u'REMOVED', u'name': u'default'}' is not string: u'default'"}`

I don't understand what is happening here; I have the filter variable set to the default `regex` where it should be obtaining every key and every security group. No matter what, even if I try to specify exact names in my `vars` file, it still reports a `stringfilter` error.

Any help would be appreciated!

**Comment by jistr** [comment]
The first issue with `no_log` is indeed something we've hit before [1] and didn't find a way to overcome it. Unfortunately no_log does not affect just logging, but also output to internal Ansible variables, and there does not seem to be a way to disable it globally.

The likely cause is that there is some string that appears in one of the auth dictionaries and then it gets censored everywhere else too. The deeper issue is that no_log is generally meant for passwords only, but the OpenStack modules (and transitively OS Migrate too) accept password nested in an `auth` dict, and no_log cannot be set on a part of a dict, so it is on the whole dict. Even non-password values from the `auth` dict then get marked as secrets and get censored.

So this problem transcends OS Migrate and affects Ansible + OpenStack in general [2]. Apparently fixing this is not straightforward [3], the only remedy we've been able to apply so far is trying to make sure the auth dicts don't contain values that may appear elsewhere. This is quite difficult and unpleasant when it comes to user names and project names...

[1] https://github.com/os-migrate/os-migrate/issues/197
[2] https://github.com/ansible/ansible/issues/54332
[3] https://github.com/ansible/ansible/issues/54332#issuecomment-494330899

--------------

The 2nd issue however looks like a different problem. What Python version are you using? Can you try with a recent Python (perhaps 3.8 or so) and maybe even in virtualenv? As described in:

https://os-migrate.github.io/os-migrate/user/install-from-galaxy.html#using-virtualenv

**Comment by njnatale-lm** [comment]
@jistr Thank you for the detailed information on the first issue.

Regarding the 2nd:
* I'm using version `3.6.8` (the latest available through normal RHEL 7.9 channels)
* I have **not** tried a `virtualenv` yet, but I will do that and report back!

**Comment by njnatale-lm** [comment]
I appear to get the same error when I use version `3.8.11` of Python (through RH SCL).

Will still try to do it within a `virtualenv` just in case.

**Comment by jistr** [comment]
I still wonder whether the `ansible-playbook` command that you are launching uses Python 3 to run itself. You should be able to see with `ansible-playbook --version`, it reports also a Python version.

The values are failing this check it seems: https://github.com/os-migrate/os-migrate/blob/c265c0ba15f075f90979c4fef5075fba376ecae8/os_migrate/plugins/filter/stringfilter.py#L44

And i can only reproduce the low level issue on Python 2:

```
$ python2
Python 2.7.18 (default, May 19 2021, 00:00:00) 
[GCC 11.1.1 20210428 (Red Hat 11.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> my_string = u'something'
>>> isinstance(my_string, str)
False
```

but not on Python 3:
```
$ python3
Python 3.9.7 (default, Aug 30 2021, 00:00:00) 
[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> my_string = u'something'
>>> isinstance(my_string, str)
True
```

So that makes me wonder whether somehow the `ansible-playbook` command uses Python 2 to execute itself (i think Python 2 is the default system Python in RHEL 7.x, so that would make sense).

Using the virtualenv steps should fix that, since the virtualenv setup command specifically refers to `python3`.

**Comment by njnatale-lm** [comment]
@jistr You were right.

I guess I thought adding this line to my `vars` file would have been sufficient:

```
ansible_python_interpreter: /opt/rh/rh-python38/root/usr/bin/python3.8
```

But it must not do quite what I think it does; I think my main issue is that RHEL 7 ships with Ansible as an RPM, and that version was built with Python 2, and not Python 3. I had never previously installed Ansible using `pip` before, so I foolishly assumed the RPM-based version was sufficient.

It may not be a bad idea if the [install page](https://os-migrate.github.io/os-migrate/user/install-from-galaxy.html) explicitly states that Ansible should be sourced via `pip` and not `yum`. I admit that I would have been fine if I used `virtualenv` from the start, but I guess since it wasn't the first thing listed, I assumed that was more of an alternative.

**Comment by jistr** [comment]
Thanks, i've posted a docs fix at https://github.com/os-migrate/os-migrate/pull/493

**Comment by njnatale-lm** [comment]
Perfect! Thank you for the help @jistr
