### ISSUE TITLE
Devstack installation is broken

### ISSUE THREAD

**Issue by fao89** [os-migrate/os-migrate#585]
CI:
```
The following packages have unmet dependencies:
 postgresql-server-dev-all : Depends: postgresql-common (= 238) but 246.pgdg22.04+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
https://github.com/os-migrate/os-migrate/actions/runs/3909506016/jobs/6680721753#step:17:1866

vagrant:
```
"        + ./stack.sh:main:235                      :   echo 'WARNING: this script has not been tested on f35'",
          "WARNING: this script has not been tested on f35",
          "+ ./stack.sh:main:236                      :   [[ '' != \\y\\e\\s ]]",
          "+ ./stack.sh:main:237                      :   die 237 'If you wish to run this script anyway run with FORCE=yes'",
          "+ functions-common:die:264                 :   local exitcode=0",
          "+ functions-common:die:265                 :   set +o xtrace",
          "[Call Trace]",
          "./stack.sh:237:die",
          "[ERROR] ./stack.sh:237 If you wish to run this script anyway run with FORCE=yes"]}
```

**Comment by jistr** [comment]
cc @ccamacho 

Looking at current devstack, they've moved onto supporting Fedora 36:

https://github.com/openstack/devstack/blob/69d71cfdf9c24d48fbea366714f4595cbd120723/stack.sh#L232

While our setup still uses Fedora 35:

```
$ grep -ri fedora35 toolbox/

toolbox/vagrant/vagrant-config.yml:  box: fedora35
toolbox/vagrant/vagrant-up:if ! vagrant box list | grep fedora35 &> /dev/null; then
toolbox/vagrant/vagrant-up:    vagrant box add --name fedora35 https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-35-1.2.x86_64.vagrant-libvirt.box
```

So moving onto F36 should fix that particular Vagrant issue.

The CI issue looks strange, like some inconsistency in Ubuntu repos. I wonder if we should try `sudo apt-get clean` before we start installing packages in the functional job... https://github.com/os-migrate/os-migrate/blob/main/.github/workflows/consistency-functional.yml#L104

**Comment by fao89** [comment]
@jistr it worked with fedora 36
https://github.com/os-migrate/os-migrate/pull/587

**Comment by fao89** [comment]
fixed by https://github.com/os-migrate/os-migrate/pull/586
