### ISSUE TITLE
[RFE] Choose destination compute node

### ISSUE THREAD

**Issue by enothen** [os-migrate/os-migrate#601]
I would like to be able to select the target compute node when migrating workloads. This could be achieved using availability zones, as explained on the Nova documentation [here](https://docs.openstack.org/nova/latest/admin/availability-zones.html#using-availability-zones-to-select-hosts).

**Comment by cloudguruab** [comment]
@enothen Hey it looks like we already have some sort of support for availability zone targets, does this work?
