### ISSUE TITLE
Question regarding os-migrate and very recent versions of openstacksdk and openstack

### ISSUE THREAD

**Issue by tibeer** [os-migrate/os-migrate#605]
Hi all,

I came across this project a few days ago and started my testing today. Unfortunately it seems that I have "too" new versions. openstacksdk is on 1.1.0, my OpenStack environments are on Zed.

E.g. when running the _export_networks.yml_ playbook, I run into issues because variable names have changed:
https://github.com/os-migrate/os-migrate/blob/main/os_migrate/roles/export_networks/tasks/main.yml#L14

`src_networks_info.openstack_networks` is not working any more for example, but `src_networks_info.networks` is.

If my observation is true, I guess a lot has to be changed in the roles?

Kind regards
tibeer

**Comment by jistr** [comment]
Yes, openstacksdk changed a lot starting with version 0.99. For now we use a pin for the SDK [1], but at some point we should refactor to switch to the new SDK.

[1] https://os-migrate.github.io/os-migrate/user/install-from-galaxy.html#using-virtualenv-for-prerequisites

**Comment by tibeer** [comment]
Awesome, thanks a lot!
