### ISSUE TITLE
Question regarding inter-cloud-migration - stuck at expose source volume

### ISSUE THREAD

**Issue by tibeer** [os-migrate/os-migrate#606]
Hi, I have a scenario, where a workload needs to be shifted from one cloud to another. Both clouds are operated by different companies. In my test-use-case I deployed a small VM in cloud A and followed the usual steps. When it comes to `import_workloads.yml`, the ansible run get's stuck at "expose source volume". The VM has only 5GB of root disk, `boot_disk_copy` is enabled. A volume is also created in cloud A for the root disk, it's also attached the the `os_migrate_conv_src` VM. But when I look into the migrate VM's processes, I cannot find any copy action happening to the migrate VM in cloud B. Is this even supported or out of scope?

**Comment by jistr** [comment]
Yes this should be supported, but at the "expose source volume" there wouldn't be any copying to cloud B happening just yet. It should just snapshot the source VM, convert the snapshot into a volume, attach the volume on source conv. host and expose it via NBD (localhost only at that time). So it should be debugged why the expose step is getting stuck.

Here's a fuller description of the workload migration sequence: https://os-migrate.github.io/os-migrate/user/how-it-works-workload-migration.html

**Comment by tibeer** [comment]
Closing this as it is not in scope any more.
