### ISSUE TITLE
Docs mention CentOS 8 images which are EOL

### ISSUE THREAD

**Issue by jistr** [os-migrate/os-migrate#614]
In workload migration docs we mention and link CentOS 8 images, but they are EOL and don't work anymore. It should be CentOS Stream 8 or we can try if CentOS Stream 9 works and switch to that directly, since that will provide more longevity. (CentOS Stream 8 will go EOL sometime mid-2024.)

https://os-migrate.github.io/os-migrate/user/walkthrough.html#workload-migration

**Comment by cloudguruab** [comment]
#615 patched in the following PR
